[package]
name = "diesel-doc-test"
version = "0.1.0"
authors = ["Naughie <masaton@naughie.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
